[package]
name = "socket-programming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4" # for log
env_logger = "0.6.1" # for log
failure = "0.1.5" # for error handling
